### ISSUE TITLE
OpenAPI support for map fields

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/openapi-tools#1013]
**Description:**

The current OpenAPI document is not supporting map field in the representation.

> Related to the [new HATEOAS Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/2391) 

**Describe your problem(s)**

Consider the following example : 
```ballerina
import ballerina/openapi;
import ballerina/http;

public type Link record {
    string rel?;
    string href;
    string[] types?;
    string[] methods?;
};

public type Location record {|
    map<Link> _links;
    string name;
    string id;
    string address;
|};

@openapi:ServiceInfo {
    embed: true
}
service on new http:Listener(9090) {
    resource function get locations() returns Location {
        return {
            name: "Alps",
            id: "l1000",
            address: "NC 29384, some place, switzerland",
            _links: {
                room: {
                    href: "/snowpeak/locations/{id}/rooms",
                    methods: ["GET"]
                }
            }
        };
    }
}
```

Call the endpoint to retrieve the OpenAPI doc : 
```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "",
    "version" : "0.1.0"
  },
  "servers" : [ {
    "url" : "{server}:{port}",
    "variables" : {
      "server" : {
        "default" : "http://localhost"
      },
      "port" : {
        "default" : "9090"
      }
    }
  } ],
  "paths" : {
    "/locations" : {
      "get" : {
        "operationId" : "getLocations",
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Location"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Location" : {
        "required" : [ "_links", "address", "id", "name" ],
        "type" : "object",
        "properties" : {
          "_links" : { },
          "name" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

As you could see the `_links` field in the schema does not have any information about the `Links` record.

**Describe your solution(s)**

According to [Swagger docs](https://swagger.io/docs/specification/data-models/dictionaries/) the schema can be represented as follows:

```json
{
"Link":{
  "required":["href"],
  "type":"object",
  "properties":{
   "rel":{
    "type":"string"
   },
   "href":{
    "type":"string"
   },
   "types":{
    "type":"array",
    "items": {
     "type":"string"
    }
   },
   "methods":{
    "type":"array",
    "items": {
     "type":"string"
    }
   }
  }
 },
"Location":{
  "required":["_links", "address", "id", "name"],
  "type":"object",
  "properties":{
    "_links":{
     "type":"object",
     "additionalProperties":{
      "$ref" : "#/components/schemas/Link"
     }			
    },
    "name":{
     "type":"string"
    },
    "id":{
     "type":"string"
    },
    "address":{
     "type":"string"
    }
   }
 },
}
```

**Comment by lnash94** [comment]
- [ ] map data type with primitive value
```ballerina
public type Location record {|
   map<string> _links?;
   string name;
|};
```
```openapi 
Location:
      required:
      - name
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: string 
        name:
          type: string
```

- [ ] map data type with record value
```ballerina
public type Location record {|
   map<string> _links?;
   string name;
|};
```
```openapi 
Location:
      required:
      - name
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: string
        name:
          type: string
```
- [ ] map data type with record value
```ballerina
public type Location record {|
   map<string> _links?;
   string name;
|};
```
```openapi 
Location:
      required:
      - name
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: string
        name:
          type: string
```

> **Description:**
> 
> The current OpenAPI document is not supporting map field in the representation.
> 
> > Related to the [new HATEOAS Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/2391)
> 
> **Describe your problem(s)**
> 
> Consider the following example :
> 
> ```ballerina
> import ballerina/openapi;
> import ballerina/http;
> 
> public type Link record {
>     string rel?;
>     string href;
>     string[] types?;
>     string[] methods?;
> };
> 
> public type Location record {|
>     map<Link> _links;
>     string name;
>     string id;
>     string address;
> |};
> 
> @openapi:ServiceInfo {
>     embed: true
> }
> service on new http:Listener(9090) {
>     resource function get locations() returns Location {
>         return {
>             name: "Alps",
>             id: "l1000",
>             address: "NC 29384, some place, switzerland",
>             _links: {
>                 room: {
>                     href: "/snowpeak/locations/{id}/rooms",
>                     methods: ["GET"]
>                 }
>             }
>         };
>     }
> }
> ```
> 
> Call the endpoint to retrieve the OpenAPI doc :
> 
> ```json
> {
>   "openapi" : "3.0.1",
>   "info" : {
>     "title" : "",
>     "version" : "0.1.0"
>   },
>   "servers" : [ {
>     "url" : "{server}:{port}",
>     "variables" : {
>       "server" : {
>         "default" : "http://localhost"
>       },
>       "port" : {
>         "default" : "9090"
>       }
>     }
>   } ],
>   "paths" : {
>     "/locations" : {
>       "get" : {
>         "operationId" : "getLocations",
>         "responses" : {
>           "200" : {
>             "description" : "Ok",
>             "content" : {
>               "application/json" : {
>                 "schema" : {
>                   "$ref" : "#/components/schemas/Location"
>                 }
>               }
>             }
>           }
>         }
>       }
>     }
>   },
>   "components" : {
>     "schemas" : {
>       "Location" : {
>         "required" : [ "_links", "address", "id", "name" ],
>         "type" : "object",
>         "properties" : {
>           "_links" : { },
>           "name" : {
>             "type" : "string"
>           },
>           "id" : {
>             "type" : "string"
>           },
>           "address" : {
>             "type" : "string"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> As you could see the `_links` field in the schema does not have any information about the `Links` record.
> 
> **Describe your solution(s)**
> 
> According to [Swagger docs](https://swagger.io/docs/specification/data-models/dictionaries/) the schema can be represented as follows:
> 
> ```json
> {
> "Link":{
>   "required":["href"],
>   "type":"object",
>   "properties":{
>    "rel":{
>     "type":"string"
>    },
>    "href":{
>     "type":"string"
>    },
>    "types":{
>     "type":"array",
>     "items": {
>      "type":"string"
>     }
>    },
>    "methods":{
>     "type":"array",
>     "items": {
>      "type":"string"
>     }
>    }
>   }
>  },
> "Location":{
>   "required":["_links", "address", "id", "name"],
>   "type":"object",
>   "properties":{
>     "_links":{
>      "type":"object",
>      "additionalProperties":{
>       "$ref" : "#/components/schemas/Link"
>      }			
>     },
>     "name":{
>      "type":"string"
>     },
>     "id":{
>      "type":"string"
>     },
>     "address":{
>      "type":"string"
>     }
>    }
>  },
> }
> ```

+1

**Comment by lnash94** [comment]
@shafreenAnfar, @TharmiganK Could you please verify these ballerina scenarios support in the http as well 🙂  ?

**Comment by TharmiganK** [comment]
LGTM 👍
