### ISSUE TITLE
Swagger Generation - Switching Version Between v3 and v2

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/openapi-tools#104]
Due to some tools still supporting only Swagger v2, e.g. WSO2 APIM 2.6. Can we provide the support in the Ballerina tool to provide an optional Swagger/OpenAPI generation version?.

**Comment by lnash94** [comment]
This issue is duplicated with this issue https://github.com/ballerina-platform/openapi-tools/issues/1091 . Therefore closed this issue
