### ISSUE TITLE
servers tag in openapi

### ISSUE THREAD

**Issue by munishase** [ballerina-platform/openapi-tools#112]
There is an object 'servers' in openapi to specify environments. if there are more than one servers(like dev and prod) and need to know which server is selected at run time in nodejs code then how can it be achieved?

**Comment by lnash94** [comment]
Currently, we support generating only one server URL by selecting the first server URL that given under the server section in OpenAPI Specification in the OpenAPI to Ballerina Command.

**Comment by aneeshafedo** [comment]
Since the users can over ride the URL when initializing the connector, this issue is already handled.
