### ISSUE TITLE
Issue with default value assigning in specific type for string  

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1219]
**Description:**
When the string has default value <|endoftext|> , it didn't add properly to code generation. It added without double quotation mark
example openapi
```openapi
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        prompt:
          default: <|endoftext|>
          nullable: true
          oneOf:
            - type: string
            - type: array
              items:
                type: string
 ```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/openapi-tools/pull/1221
