### ISSUE TITLE
Missing json conversion in resources with custom mimetypes

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1265]
**Description:**
When generating the [vimeo connector ](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/vimeo/openapi.yml)using the OpenAPI tool in Ballerina Swan Lake 2201.4.1 version, `payload.toJson` statement is missing in few resources and that gives a compile time error. 
\
![image](https://user-images.githubusercontent.com/34091327/228133717-fa1709c2-389a-479b-8b4a-10fda83ab520.png)

**Steps to reproduce:**

**Affected Versions:**

Ballerina Swan Lake 2201.4.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
Issue is only for the custom media types which are extended from know media type. Proposing to generate the request of such type following the known media type's syntax. As an example below code can be generated for above example.

**Sample OpenAPI** 

```yaml
  /pet:
    put:
      tags:
        - pet
      summary: Update an existing pet
      description: Update an existing pet by Id
      operationId: updatePet
      requestBody:
        description: Update an existent pet in the store
        content:
          application/vnd.vimeo.channel+json:
            schema:
              properties:
                id:
                  type: integer
                  format: int64
                  example: 10
                name:
                  type: string
                  example: doggie
                category:
                  $ref: '#/components/schemas/Category'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'          
```

```bal
    remote isolated function updatePet(Pet_body payload) returns Pet|error {
        string resourcePath = string `/pet`;
        http:Request request = new;
        json jsonBody = payload.toJson();
        request.setPayload(jsonBody, "application/vnd.petstore.channel+json");
        Pet response = check self.clientEp->put(resourcePath, request);
        return response;
    }
```

@NipunaRanasinghe @lnash94 Appreicate your thoughts on this matter.

**Comment by NipunaRanasinghe** [comment]
> Issue is only for the custom media types which are extended from know media type. Proposing to generate the request of such type following the known media type's syntax. As an example below code can be generated for above example.
> 
> **Sample OpenAPI** 
> 
> ```yaml
>   /pet:
>     put:
>       tags:
>         - pet
>       summary: Update an existing pet
>       description: Update an existing pet by Id
>       operationId: updatePet
>       requestBody:
>         description: Update an existent pet in the store
>         content:
>           application/vnd.vimeo.channel+json:
>             schema:
>               properties:
>                 id:
>                   type: integer
>                   format: int64
>                   example: 10
>                 name:
>                   type: string
>                   example: doggie
>                 category:
>                   $ref: '#/components/schemas/Category'
>         required: true
>       responses:
>         '200':
>           description: Successful operation
>           content:
>             application/json:
>               schema:
>                 $ref: '#/components/schemas/Pet'          
> ```
> 
> ```bal
>     remote isolated function updatePet(Pet_body payload) returns Pet|error {
>         string resourcePath = string `/pet`;
>         http:Request request = new;
>         json jsonBody = payload.toJson();
>         request.setPayload(jsonBody, "application/vnd.petstore.channel+json");
>         Pet response = check self.clientEp->put(resourcePath, request);
>         return response;
>     }
> ```
> 
> @NipunaRanasinghe @lnash94 Appreicate your thoughts on this matter. 

+1 for using the known media type in similar scenarios. Also lets make sure to add the relavant test cases and also verify the behavior for custom media types extended from other known media rypes 
(e.g. custom.mediatype+xml)

**Comment by lnash94** [comment]
Close with this PR https://github.com/ballerina-platform/openapi-tools/pull/1313
