### ISSUE TITLE
Need to specify the default http version when generating the connector

### ISSUE THREAD

**Issue by isuruRuhu** [ballerina-platform/openapi-tools#1270]
**Description:**
Need to specify the default http version when generating the connector

**Describe your problem(s)**
I'm trying to generate connectors for Azure openAI service. They only support the HTTP_1_1 version. But when I generate the connector default value for the HTTP version is set to HTTP_2_0. Need to have the default HTTP version as HTTP_1_1. This way user has to manually define the HTTP version in the configs. 

**Describe your solution(s)**
Add a custom tag to specify the HTTP version

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
The proposed OpenAPI extension would be a extension added to the root level of the OpenAPI, applying the http version when configuring the client. All the resources within that client will use the given http version. If not defined, default version from ballerina/http module will be used. 

```bal
x-ballerina-http-configurations:
  httpVersion: "1.1"
```

![image](https://user-images.githubusercontent.com/34091327/228451682-0b8c34e3-024a-4649-9535-f7a871d1d67e.png)

**Comment by lnash94** [comment]
Close with this PR https://github.com/ballerina-platform/openapi-tools/pull/1313
