### ISSUE TITLE
Use ProjectAPI API for Ballerina to OpenAPI Code generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1275]
**Description:**
We use a Syntax tree and Semantic Model for the code generation for the Current ballerina to the OpenAPI tool. Recently we have identified several scenarios in which we cannot achieve only using the Syntax tree and Semantic Model. Therefore we have to take ProjectAPI as well.
The issues we can not solve only using the Syntax tree and Semantic Model
1. https://github.com/ballerina-platform/openapi-tools/issues/1040
2. https://github.com/wso2-enterprise/internal-support-ballerina/issues/275

Meeting Notes that we discuss using projectAPI: https://docs.google.com/document/d/12qmNTOAZMvii0dFLcwcKh9JHZHnSn_ZeeZLjgJdZGjM/edit

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/openapi-tools/pull/1209
