### ISSUE TITLE
Support integer format types to openAPI to Ballerina code generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1286]
**Description:**
When an integer has the below format, then the ballerina `int` type can be supported with the given formats 
integer | – | Integer numbers.
-- | -- | --
integer | int32 | Signed 32-bit integers (commonly used integer type).
integer | int64 | Signed 64-bit integers (long type).

- Check another integer type as well such as unsigned, singed  
- Find another integer format like unsign, or sign that can have an integer format
- Check the support with record fields
- Check the support with query, path, header and request body support
- Check the constraint support

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
@VimukthiRajapaksha is working on this issue

**Comment by VimukthiRajapaksha** [comment]
We have analyzed the Swagger and Ballerina specifications. Currently, the [OpenAPI 3.0 specification](https://swagger.io/docs/specification/data-models/data-types/#numbers) supports both Signed 32-bit and Signed 64-bit integers. We tested the capability of the [Signed32](https://ballerina.io/spec/lang/master/#built-in_subtypes) built-in subtype to add this functionality to the Ballerina OpenAPI tools. As of now, this approach won't work well with the Ballerina Constraint, Query Parameter, Path Parameter, and HTTP Request Header scenarios. Is it possible to use the `int:Signed32` with those places as well?

Sample OpenAPI definition

```
schemas:
    Album:
      type: object
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 25
        likes:
          type: integer
          format: int64
        shares:
          type: integer
          example: int32
```

### Usages of the [Signed32](https://ballerina.io/spec/lang/master/#built-in_subtypes) built-in subtype

#### 1. Use with a Constraint
``` 
@constraint:Int {
  minValue: 1
}
int:Signed32 id;
```
Result: ```invalid `@constraint:Int` annotation on `int:Signed32` type(CONSTRAINT_101)```

#### 2. Use as an query parameter
```
resource function get albums(int:Signed32 'limit, int downloads) 
    returns Album[] {
```
Result: ``` invalid resource parameter type: ballerina/lang.int:0.0.0:Signed32(HTTP_106) ```

#### 3. Use as a path parameter
```
resource function get albums/[int:Signed32 id]() returns Album? {
```
Result: ``` error: incompatible path parameter type: 'Signed32' ```

#### 4. Use as a request header
```
resource function get albums(@http:Header int:Signed32 x\-transaction\-id) returns Album[] {
```
Result: ``` invalid type of header param x\-transaction\-id: One of the following types is expected: string,int,float,decimal,boolean, an array of the above types or a record which consists of the above types(HTTP_109) ```

#### 5. Use in request/response body
```
type Album record {|
   string title;
   int:Signed32 shares;
   int likes;
|};
```
Result: Returns the expected result. An error similar to the below returns for invalid request bodies
```
data binding failed: {ballerina/lang.value}ConversionError, {"message":"'map<json>' value cannot be converted to 'signed_integer_test:record {| int:Signed32 shares; string title; int likes; |}': 
		field 'likes' in record 'signed_integer_test:record {| int:Signed32 shares; string title; int likes; |}' should be of type 'lang.int:Signed32', found '922337203
```

**Comment by lnash94** [comment]
@shafreenAnfar Appreciate your thoughts regarding the support of the `int:Singed32` type in query, path, and header parameters. (above-mentioned [1.1](https://github.com/ballerina-platform/openapi-tools/issues/1286#:~:text=1.1%3A%20Use%20with%20a%20Constraint) - [1.4](https://github.com/ballerina-platform/openapi-tools/issues/1286#:~:text=1.4%3A%20Use%20as%20a%20request%20header) scenarios) 🙂

**Comment by lnash94** [comment]
From my understanding, If we pick Approach 2, we will have to be concerned with handling constraint support since we still cannot use a constraint in the path, query, and header parameters, which is not the case with Approach 1.

Therefore I think Approach 1 (using the Signed32 built-in subtype) would be the ideal mapping to represent the 32-bit integer format since we can map it in the Ballerina language.
We have to pay attention to handling the error message in BFSI use cases[1], as it may have a data-binding error rather than a validation error message when using Approach 1.

@NipunaRanasinghe , @aneeshafedo WDYT?
 
[1] email-thread: [Inquiry] Generating Ballerina Services using the OpenAPI CLI tool

**Comment by shafreenAnfar** [comment]
Yes, I also agree. Seems there is some improvements we need to do in both constraint and http module. 

@TharmiganK @dilanSachi

**Comment by TharmiganK** [comment]
With the compiler rewrite of HTTP module, the above inconsistent compiler bugs are fixed. So the following scenarios, 1.2, 1.3, 1.4 and 2.2 should work with `2201.5.0`.

And the compiler errors from constraint seems to be a bug will check on that. Also we have a plan to support [constraint support for http query and header parameters](https://github.com/ballerina-platform/ballerina-standard-library/issues/3239).

**Comment by lnash94** [comment]
@shafreenAnfar, @TharmiganK Thank you for the inputs, we will keep in touch on the tracking issues https://github.com/ballerina-platform/ballerina-standard-library/issues/3239, https://github.com/ballerina-platform/ballerina-standard-library/issues/4349.

> With the compiler rewrite of HTTP module, the above inconsistent compiler bugs are fixed. So the following scenarios, 1.2, 1.3, 1.4 and 2.2 should work with `2201.5.0`.

 With this seems we have no major blocker for Approach 01

**Comment by NipunaRanasinghe** [comment]
> @shafreenAnfar, @TharmiganK Thank you for the inputs, we will keep in touch on the tracking issues [ballerina-platform/ballerina-standard-library#3239](https://github.com/ballerina-platform/ballerina-standard-library/issues/3239), [ballerina-platform/ballerina-standard-library#4349](https://github.com/ballerina-platform/ballerina-standard-library/issues/4349).
> 
> > With the compiler rewrite of HTTP module, the above inconsistent compiler bugs are fixed. So the following scenarios, 1.2, 1.3, 1.4 and 2.2 should work with `2201.5.0`.
> 
> With this seems we have no major blocker for Approach 01

+1 to proceed with option 1 as IMO we better stick to the builtin types as much as possible without creating custom types for the same purpose.
