### ISSUE TITLE
Provide support for query parameters with referenced schema in Ballerina service generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1331]
**Description:**

Sample OpenAPI

```yaml
 parameters:
        - description: "Meeting location"
          in: query
          name: location
          schema:
            $ref: '#/components/schemas/RoomNo'
```

Currently, an OpenAPI definition with above type parameter givs below error message. 

`Error while generating the service. Query parameters with type 'null' can not be mapped to the Ballerina query parameters.`

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
The supported types for resource function query parameters are string, int, float, boolean, decimal, and the array types of the aforementioned types. ([Reference](https://ballerina.io/spec/http/#2423-resource-methods:~:text=The%20supported%20types%20are%20string%2C%20int%2C%20float%2C%20boolean%2C%20decimal%2C%20and%20the%20array%20types%20of%20the%20aforementioned%20types.))

Therefore the fix for this issue will be addressed the reference schemas of above mentioned types. 

Example:

```yaml
paths:
  /users/meetings:
    get:
      description: List all the meetings that were scheduled
      operationId: listMeetings
      parameters:
        - description: "Meeting location"
          in: query
          name: location
          schema:
            $ref: '#/components/schemas/RoomNo'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeetingList'
          description: "HTTP Status Code:200. List of meetings returned."
components:
  schemas:
    RoomNo:
      enum:
        - R1
        - R3
        - R5
      type: string
      nullable: true
```

**Proposed generation**

```bal
public type RoomNo string;

     resource function get users/meetings(RoomNo location) {
     }

```

Please note that due to the [bug](https://github.com/ballerina-platform/ballerina-standard-library/issues/4374) in http module in a scenario where the referenced parameter is `nullable: true` the generated code gives an compiler error. 

Ex: 

```bal
public type RoomNo string?;

     resource function get users/meetings(RoomNo location) {
     }
```

@TharmiganK is working on the fix and hoping to add in Update 6. 

@NipunaRanasinghe @lnash94 appreciate your feedback.

**Comment by NipunaRanasinghe** [comment]
> The supported types for resource function query parameters are string, int, float, boolean, decimal, and the array types of the aforementioned types. ([Reference](https://ballerina.io/spec/http/#2423-resource-methods:~:text=The%20supported%20types%20are%20string%2C%20int%2C%20float%2C%20boolean%2C%20decimal%2C%20and%20the%20array%20types%20of%20the%20aforementioned%20types.))
> 
> Therefore the fix for this issue will be addressed the reference schemas of above mentioned types.
> 
> Example:
> 
> ```yaml
> paths:
>   /users/meetings:
>     get:
>       description: List all the meetings that were scheduled
>       operationId: listMeetings
>       parameters:
>         - description: "Meeting location"
>           in: query
>           name: location
>           schema:
>             $ref: '#/components/schemas/RoomNo'
>       responses:
>         "200":
>           content:
>             application/json:
>               schema:
>                 $ref: '#/components/schemas/MeetingList'
>           description: "HTTP Status Code:200. List of meetings returned."
> components:
>   schemas:
>     RoomNo:
>       enum:
>         - R1
>         - R3
>         - R5
>       type: string
>       nullable: true
> ```
> 
> **Proposed generation**
> 
> ```ballerina
> public type RoomNo string;
> 
>      resource function get users/meetings(RoomNo location) {
>      }
> ```
> 
> Please note that due to the [bug](https://github.com/ballerina-platform/ballerina-standard-library/issues/4374) in http module in a scenario where the referenced parameter is `nullable: true` the generated code gives an compiler error.
> 
> Ex:
> 
> ```ballerina
> public type RoomNo string?;
> 
>      resource function get users/meetings(RoomNo location) {
>      }
> ```
> 
> @TharmiganK is working on the fix and hoping to add in Update 6.
> 
> @NipunaRanasinghe @lnash94 appreciate your feedback.

@aneeshafedo +1 to go ahead with the aforementioned implementation. Probably we can generate the `nullable: true` reference types without the nil type until we get the fix from the HTTP side in update 6. WDYT?
