### ISSUE TITLE
Add support for header parameters with reference in Ballerina service generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1350]
**Description:**
$subject

**OpenAPI Example:** 

```yaml
paths:
  /pet:
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      parameters:
        - name: Content-ID
          in: header
          description: ID of pet to return
          required: true
          schema:
            $ref: '#/components/schemas/content_id'  
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'          
components:
  schemas:
    content_id:
      type: string
```
**Describe your problem(s)**
When generating service from this it returns below error

`Error occurred when generating service for OpenAPI contract at openapi.yaml. Unsupported OAS data type `null`.`

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by aneeshafedo** [comment]
The error also found in this OB yaml https://github.com/wso2-enterprise/ob-compliance-toolkit-berlin/blob/b166d794f6683c11055dd3bf4e27ae049bec9859/toolkits/ob-apim/repository/resources/apis/berlin.group.org/PSD2API_1.3.6/psd2-api_1.3.6_20200327.yaml

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/openapi-tools/pull/1355
