### ISSUE TITLE
Provide Record type support for Query parameter in Service generation 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1384]
**Description:**
Supporting Record type as a query parameter will be available with the Http module along with the Ballerina Swan Lake 2201.6.0 version. Therefore there is the possibility to map Object schema into a record when it has a Query parameter scheme. 

- When the query parameter has an inline object
- When the query parameter has a reference object
- When the query parameter has an object array

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Closing with https://github.com/ballerina-platform/openapi-tools/pull/1389 and https://github.com/ballerina-platform/openapi-tools/pull/1393
