### ISSUE TITLE
OpenAPI LS Extension returns wrong response without running the code modifier

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/openapi-tools#1401]
**Description:**

We have introduced a default http payload parameter support in 2201.5.x. It automatically adds the payload annotation to a compatible signature parameter type using the code modifier. This change has been adhered to open API-tools by running the code modifiers before generating the document. But seems like we have missed adding this to the LS extension which is used for `Try it` feature in the VS code.

**Steps to reproduce:**

Use the [following BBE ](https://ballerina.io/learn/by-example/http-service-data-binding/)in the VS code and click on the `Try it` option to see the openAPI. The parameter is shown as a query parameter.

This `Try it` feature uses the `openAPILSExtension/generateOpenAPI` API to generate the openAPI. 

**Affected Versions:**

2201.5.x, 2201.6.0

**Comment by aneeshafedo** [comment]
Sample Swagger after the fix 

![](https://github.com/ballerina-platform/openapi-tools/assets/34091327/f2ace811-8852-485a-8f79-830fc52ff033)
