### ISSUE TITLE
Improve client response handling for multiple responses without payload 

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#285]
**Description:**
Response handling for the below swagger scenario will not bind the 403,404 status for error. Currently generated client only map those every status to http:Response.

**Generated ballerina code**
```ballerina
remote isolated function removeAttachment(string id) returns error? {
        string  path = string `/rest/api/2/attachment/${id}`;
        http:Request request = new;
        //TODO: Update the request as needed;
         _ = check self.clientEp-> delete(path, request, targetType =http:Response);
    } 
```
**OpenAPI swagger**
```
responses:
        '204':
          description: Returned if the request is successful.
        '403':
          description: Returned if the user does not have the necessary permission.
        '404':
          description: |-
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lnash94** [comment]
Our current code generation is below
```ballerina
# Returns pet inventories by status
    #
    # + return - Returned if the request is successful. 
    resource isolated function get store/inventory() returns http:Response|error {
        string resourcePath = string `/store/inventory`;
        http:Response response = check self.clientEp->get(resourcePath);
        return response;
    }
```
We have some thoughts on implementing this with a binding status code like the below way
**Suggested approach**
```ballerina
resource isolated function get store/inventory() returns http:Ok|error {
        string resourcePath = string `/store/inventory`;
        http:Ok response = check self.clientEp->get(resourcePath);
        return response;
    }
```
@chamil321 Cloud you please let us know whether this approach is feasible to do?

**Comment by chamil321** [comment]
> Our current code generation is below
> 
> ```ballerina
> # Returns pet inventories by status
>     #
>     # + return - Returned if the request is successful. 
>     resource isolated function get store/inventory() returns http:Response|error {
>         string resourcePath = string `/store/inventory`;
>         http:Response response = check self.clientEp->get(resourcePath);
>         return response;
>     }
> ```
> 
> We have some thoughts on implementing this with a binding status code like the below way **Suggested approach**
> 
> ```ballerina
> resource isolated function get store/inventory() returns http:Forbidden|error {
>         string resourcePath = string `/store/inventory`;
>         http:Forbidden response = check self.clientEp->get(resourcePath);
>         return response;
>     }
> ```
> 
> @chamil321 Cloud you please let us know whether this approach is feasible to do?

This is not supported in HTTP yet. For the moment, we allow payload binding in addition to the http:Response. 
This feature is doable. But need to think of defining the payload type for binding. The StatusCodeRecord has the body field and it's type is `anydata`. During the StatusCodeRecord creating, the inbound response payload should be converted to any of the anydata. That detail is missing in suggested API design. 

@shafreenAnfar

**Comment by aneeshafedo** [comment]
Related issue https://github.com/ballerina-platform/openapi-tools/issues/1169

**Comment by aneeshafedo** [comment]
Closin the the issue is duplicated here https://github.com/ballerina-platform/openapi-tools/issues/1169
