### ISSUE TITLE
Generate API documentation for resource function

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#509]
**Description:**
Map given description in the OAS to generated resource function API doc.

**Comment by aneeshafedo** [comment]
Sample ballerina service generated for the OpenAPI contract given [here](https://gist.github.com/aneeshafedo/54206c2f3378664084595057248315c0). 

```bal
import ballerina/http;

listener http:Listener ep0 = new (80, config = {host: "petstore.openapi.io"});

service /v1 on ep0 {
    # List all pets
    #
    # + 'limit - How many items to return at one time (max 100)
    # + return - An paged array of pets
    resource function get pets(int? 'limit) returns Pets|http:Response {
        http:Response res = new;
        return res;
    }

    # Create a pet
    #
    # + return - Null response
    resource function post pets() returns http:Created|http:Response {
        http:Response res = new;
        return res;
    }

    # Info for a specific pet
    #
    # + petId - The id of the pet to retrieve
    # + return - Expected response to a valid request
    resource function get pets/[string petId]() returns Pets|http:Response {
        http:Response res = new;
        return res;
    }
}

```

**Comment by lnash94** [comment]
> Sample ballerina service generated for the OpenAPI contract given [here](https://gist.github.com/aneeshafedo/54206c2f3378664084595057248315c0).
> 
> ```ballerina
> import ballerina/http;
> 
> listener http:Listener ep0 = new (80, config = {host: "petstore.openapi.io"});
> 
> service /v1 on ep0 {
>     # List all pets
>     #
>     # + 'limit - How many items to return at one time (max 100)
>     # + return - An paged array of pets
>     resource function get pets(int? 'limit) returns Pets|http:Response {
>         http:Response res = new;
>         return res;
>     }
> 
>     # Create a pet
>     #
>     # + return - Null response
>     resource function post pets() returns http:Created|http:Response {
>         http:Response res = new;
>         return res;
>     }
> 
>     # Info for a specific pet
>     #
>     # + petId - The id of the pet to retrieve
>     # + return - Expected response to a valid request
>     resource function get pets/[string petId]() returns Pets|http:Response {
>         http:Response res = new;
>         return res;
>     }
> }
> ```
> 
> @lnash94 @NipunaRanasinghe please review

small concern regarding the return type API doc mapping: If there is a union type what will be the API doc for the return, how we pick it from OAS?

**Comment by aneeshafedo** [comment]
currently we only get the return description from the success response. 

Ex:

```yaml
responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
```

**Current generation**

```bal
# + return - An paged array of pets
```

May be we can combine all the returns into one sentence.

Ex: `# + return - An paged array of pets or unexpected error`

**Comment by aneeshafedo** [comment]
> > Sample ballerina service generated for the OpenAPI contract given [here](https://gist.github.com/aneeshafedo/54206c2f3378664084595057248315c0).
> > ```ballerina
> > import ballerina/http;
> > 
> > listener http:Listener ep0 = new (80, config = {host: "petstore.openapi.io"});
> > 
> > service /v1 on ep0 {
> >     # List all pets
> >     #
> >     # + 'limit - How many items to return at one time (max 100)
> >     # + return - An paged array of pets
> >     resource function get pets(int? 'limit) returns Pets|http:Response {
> >         http:Response res = new;
> >         return res;
> >     }
> > 
> >     # Create a pet
> >     #
> >     # + return - Null response
> >     resource function post pets() returns http:Created|http:Response {
> >         http:Response res = new;
> >         return res;
> >     }
> > 
> >     # Info for a specific pet
> >     #
> >     # + petId - The id of the pet to retrieve
> >     # + return - Expected response to a valid request
> >     resource function get pets/[string petId]() returns Pets|http:Response {
> >         http:Response res = new;
> >         return res;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @lnash94 @NipunaRanasinghe please review
> 
> small concern regarding the return type API doc mapping: If there is a union type what will be the API doc for the return, how we pick it from OAS?

currently we only get the return description from the success response. 

Ex:

```yaml
responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
```

**Current generation**

```bal
# + return - An paged array of pets
```

May be we can combine all the returns into one sentence.

Ex: `# + return - An paged array of pets or unexpected error`
