### ISSUE TITLE
Unable to set the binary payload to request body

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/openapi-tools#514]
**Description:**
Current openapi tool does not support to set binary payload to request body.

**Affected Product Version:**
SL Beta2

**Steps to reproduce:**
**openapi.yml**
```yml
 requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
```
**client.bal**
```ballerina
    remote isolated function importScanData(string siteId, string payload) returns Task|error {
        string  path = string `/org/sites/${siteId}/import`;
        http:Request request = new;
        Task response = check self.clientEp->put(path, request, targetType=Task);
        return response;
    }
```

**Comment by SanduDS** [comment]
Can be reproduce the error [by this](https://developer.mindsphere.io/api/specs/iotfile-v3-2-4.yaml).

**Comment by aneeshafedo** [comment]
Found in [iris.esignature](https://github.com/ballerina-platform/ballerinax-openapi-connectors/blob/main/openapi/iris.esignature/openapi.yml)

**Comment by lnash94** [comment]
related issue https://github.com/ballerina-platform/ballerina-openapi/issues/690
