### ISSUE TITLE
Add command-line option to generate test cases in client generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#673]
**Description:**
In the current implementation tests are generated at client generation by default. Since tests are not required for a Ballerina package it will be more user-friendly to generate test skeletons on request

Suggested command-line option

`bal openapi -i <openapi-file> --add-tests`

@lnash94 @indikasampath2000 @abeykoon WDYT ?

**Comment by indikasampath2000** [comment]
+1. Should we use `--add-tests` or `--with-tests`? The purpose of the bal command is to generate the source code. Hence `--with-tests` would make more sense as I feel.
```
bal openapi -i <openapi-file> --with-tests
```

**Comment by abeykoon** [comment]
+1 for 

```
bal openapi -i <openapi-file> --with-tests

```
