### ISSUE TITLE
Unsupported media type 'application/octet-stream' is given in the request body

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/openapi-tools#690]
**Description:**
I am trying to generate a client using the OpenAPI tool but the following error is coming:
```
Unsupported media type 'application/octet-stream' is given in the request body
```

It is probably because I have this in my OpenAPI specification:
```yaml
      requestBody:
        description: "*.bala file."
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
```

**Steps to reproduce:**

**Affected Versions:**
beta3

**OS, DB, other environment details and versions:**
Mac

**Comment by Chuhaa** [comment]
Fixed in https://github.com/ballerina-platform/openapi-tools/pull/692
