### ISSUE TITLE
Check all missing operation ids and throw error at once 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#759]
**Description:**
In the current implementation, error will be thrown in the first occurrence of missing operation id. Update the code to throw all missing operationId errors at once. 

```java
private void validateOperationIds(Set<Map.Entry<String, PathItem>> paths) throws BallerinaOpenApiException {
        for (Map.Entry<String, PathItem> entry : paths) {
            for (Operation operation : entry.getValue().readOperations()) {
                if (operation.getOperationId() != null) {
                    String operationId = getValidName(operation.getOperationId(), false);
                    operation.setOperationId(operationId);
                } else {
                    throw new BallerinaOpenApiException("OperationId is missing for the resource path: "
                            + entry.getKey());
                }
            }
        }
    }
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
Shall we return the list of string templates `"OperationId is missing for the resource path: %s" entry.getKey()`  without throwing `BallerinaOpenApiException`  in `validateOperationIds` function or generated one string message to set the exception message by concatenating all `openapiId` missing path details? WDYT?

**Comment by aneeshafedo** [comment]
@lnash94 Shall we follow the same way it has done in [`validateRequestBody` ](https://github.com/ballerina-platform/openapi-tools/blob/3a41526b98b5c7923aa31c516fe3eeb0d46c3f52/openapi-cli/src/main/java/io/ballerina/openapi/cmd/CodeGenerator.java#L620)function.

**Comment by lnash94** [comment]
yeah +1 to generate one string message to set the exception message by concatenating all openapiId missing path details 🙂
