### ISSUE TITLE
Invalid union type generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#810]
**Description:**
Bug found in [apideck.accounting](https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/apideck.accounting/openapi.yaml) OpeAPI

Generated Code
```bal
string?|decimal?|boolean?|string[] value?;
```
Expected Code
```bal
string|decimal|boolean|string[]? value?;
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by abeykoon** [comment]
We will fix only if it does not complex our code generation logic. Both are logically work in same way.
