### ISSUE TITLE
Invalid response code generated when adding return type annotation

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/openapi-tools#879]
**Description:**
Consider the following capture,

<img width="1612" alt="Screenshot 2022-01-25 at 11 12 33" src="https://user-images.githubusercontent.com/1329674/150961124-1d02b4d1-82cd-461a-b22e-6c388959cd7c.png">

The response code is shown as `202` when we add the `http:Payload` annotation to the return type. When we remove it, it shows the `200` response code.

**Comment by lnash94** [comment]
implementation has a blocker when going to resolve the mediaType in another module
example : 
```ballerina
import ballerina/mime;
import ballerina/http;

listener http:Listener helloEp = new (9090);

type User record {
    int id;
    string name;
};

@http:ServiceConfig{
    mediaTypeSubtypePrefix: "snowflake"
}
service /payloadV on helloEp {
    resource function get pet01() returns @http:Payload {mediaType: mime:APPLICATION_JSON} User {
        User user = {
            id: 1,
            name: "abc"
        };
        return user;
    } 
}
```
created issue : [https://github.com/ballerina-platform/ballerina-lang/issues/34911](https://github.com/ballerina-platform/ballerina-lang/issues/34911)

**Comment by lnash94** [comment]
This issue is closed with the favour of this PR https://github.com/ballerina-platform/openapi-tools/pull/920
