### ISSUE TITLE
Compilation error for union type payload body in generated service

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/openapi-tools#900]
**Description:**
Ballerina 2201.0.0 tool generates resource function with union type payload when `oneOf` is given in the request body and it causes compilation error while building the project.
```    
resource function put storageSpaces/[string  name](@http:Payload StoragespacesNameBody payload) returns http:Ok|http:BadRequest {
```

Error message
```
ERROR [openapi_service.bal:(6:92,6:99)] invalid payload parameter type: chuhaashanan/aaa:1.1.0:StoragespacesNameBody
error: compilation contains errors
```

**Steps to reproduce:**
Generate service from following yaml file.
```yaml
openapi: 3.0.1
info:
  title:  Storage Space
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /storageSpaces/{name}:
    put:
      summary: Put key value
      operationId: putKey
      parameters:
        - name: name
          in: path
          description: name of the storage space
          required: true
          schema:
            type: string
      requestBody:
        description: Value to be added
        content:
          application/json:
            schema:
              oneOf:
                - type: string
                - type: integer
                - type: number
                - type: object
      responses:
        200:
          description: Successful operation.
        400:
          description: Invalid storage space name supplied
```

Service file
```bal
import ballerina/http;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});

service / on ep0 {
    resource function put storageSpaces/[string  name](@http:Payload StoragespacesNameBody payload) returns http:Ok|http:BadRequest {
        http:Ok res = {};
        return res;
    }
}

public type StoragespacesNameBody string|int|decimal|record {};
```

**Affected Versions:**
Ballerina 2201.0.0

**Comment by shafreenAnfar** [comment]
@Chuhaa What is the expected response content-type of this service ?

**Comment by Chuhaa** [comment]
> @Chuhaa What is the expected response content-type of this service ?

`application/json`.

**Comment by lnash94** [comment]
Hi @Chuhaa 
We have a small concern regarding the given request Body payload content type, won't it be in the below way?
```openapi
...
requestBody:
        description: Value to be added
        content:
          text/plain:
            schema:
              oneOf:
                - type: string
                - type: integer
                - type: number
          application/json:
            schema:
              type: object
```
or 
I'm afraid that you are concerned about accepting all the oneOf type as `json`, Can't we write the openapi spec in the below way
```openapi
requestBody:
        description: Value to be added
        content:
          application/json:
            schema: {}
```
As the tool also generating invalid code, I will add a fix to get the given MIME type to the payload when it has an unsupportable type in the request body section. 🙂

**Comment by Chuhaa** [comment]
@lnash94 We use this yaml for client generation as well. So first approach won't work as only first content is considered in client generation. Second would work, but as we wanted to use union type because of more understandability in Choreo input form generation, we were thinking about `oneOf`. For now, we'll go with second approach with some manual work

**Comment by lnash94** [comment]
Related issue https://github.com/ballerina-platform/ballerina-standard-library/issues/2701

**Comment by lnash94** [comment]
This issue has been fixed via this PR https://github.com/ballerina-platform/openapi-tools/pull/906 , and it merged to master via this PR https://github.com/ballerina-platform/openapi-tools/pull/919
