### ISSUE TITLE
HTTP Client validator for OpenAPI

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/openapi-tools#907]
**Description:**
This feature will allow a user to annotate a http client and bind it to an OpenAPI Contract. Once the client is bound to a OpenAPI contract the client validator compiler plugin will check if all the following actions perform by the client conforms to the bounded OpenAPI contract.

**Comment by lnash94** [comment]
- [ ] [Finalize the OpenAPI Client Validator Spec](https://github.com/ballerina-platform/openapi-tools/issues/922)
- [ ] Finalize the design for implementation
- [ ] Implementation for validator

**Comment by hevayo** [comment]
This feature will be discontinue in support of client import specification
