### ISSUE TITLE
Nilable record is not created for nullable in component schema

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/openapi-tools#948]
**Description:**
Following openAPI component is not being generated as nilable record. But ideally it should be generated as nilable record.
```yaml
    TaskResponse:
      allOf:
        - $ref: "#/components/schemas/TaskBase"
        - properties:
            assignee:
              description: Users assigned to the task.
              $ref: "#/components/schemas/UserCompact"
              nullable: true
```

**Steps to reproduce:**
Above scenario is found in [Asana openAPI](https://raw.githubusercontent.com/ballerina-platform/openapi-connectors/main/openapi/asana/openapi.yaml)

Generated client
```bal
public type TaskResponse record {
    # The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
    UserCompact assignee?;
}
```

**Affected Versions:**
2201.0.1

**Comment by abeykoon** [comment]
This is the newly suggested way with the review. Shall we fix it in this manner? 

public type TaskResponse record {
    # The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
    UserCompact assignee = ();
}

**Comment by kapilraajP** [comment]
> This is the newly suggested way with the review. Shall we fix it in this manner?
> 
> public type TaskResponse record { # The owner of the user task list, i.e. the person whose My Tasks is represented by this resource. UserCompact assignee = (); }

This will be related to this issue and will be addressed while resolving that issue https://github.com/ballerina-platform/openapi-tools/issues/957

**Comment by kapilraajP** [comment]
This issue will be fixed by creating a nullable field as following in ballerina type generation
```
public type TaskResponse record {
    # The owner of the user task list, i.e. the person whose My Tasks is represented by this resource.
    UserCompact? assignee?;
}
```

**Comment by aneeshafedo** [comment]
Sibling values alongside $ref s are ignored. To add properties to a $ref, wrap the $ref into allOf, or move extra properties into the referenced definition. Please refer to [here](https://swagger.io/docs/specification/using-ref/#:~:text=%24ref%20and%20Sibling%20Elements) for more details.
