### ISSUE TITLE
Path parameter serialization on client is not supported in the current version

### ISSUE THREAD

**Issue by sachinira** [ballerina-platform/openapi-tools#949]
**Description:**
The path parameter serialization which is available in the OpenAPI 3.0 is not currently supported in the tool

**Describe your problem(s)**
When trying to generate the client from the tool for an OpenAPI with following component gives an error
```yaml
/api/3/accounts/bulk_delete/{ids}:
    delete:
      tags:
      - Accounts
      summary: Bulk delete accounts
      operationId: Bulkdeleteaccounts
      parameters:
      - name: ids
        in: path
        description: Array with integers representing ID's of accounts to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items: 
            type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
```

**Steps to Reproduce**
Similar scenario is found in [ActiveCampaign Rest API bulk operations](https://developers.activecampaign.com/reference/bulk-delete-accounts)

**Affected Versions**
 2201.0.1

**Comment by aneeshafedo** [comment]
Address in resolving https://github.com/ballerina-platform/openapi-tools/issues/1046
