### ISSUE TITLE
Improve nillable field support in OpenAPI to Ballerina schema generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#957]
**Description:**

In the OpenAPI schema we can specify the properties that can have `null` values as below. 
```yml
latitude:
          example: "40.759211"
          nullable: true
          type: string
```

However, we encountered that API vendors does not always mention `nullable: true` in ther OpenAPIs or in API docs correctly. When not nillable field gets a null value Ballerina http type binding for the response schema fails with a conversion error. 

To overcome this conversion issue currently we have introduced the `--nullable` flag in OpenAPI CLI tool to make all the fields nillable in a ballerina connector.  

We had a discussion to find out the most suitable solution for this matter. Find the meeting notes [here](https://docs.google.com/document/d/1LVzzLNj-I9jTllejVHR5FPwacdknUiNFvDJVNVKZhJc/edit?usp=sharing). 

Following are the solutions suggested. 

**Describe your solution(s)**
### Solution 1

**Field with default of nil**

`record { string? foo = (); }`

DO NOT DO

`record { string? foo?; }`

### Solution 2

**Handle null values in optional fields withing the http:Client itself when binding the payload to bal record.** 

More permissive fromJsonWithType

Scenario 1 : Optional field has a valid value

```
json j = { foo: "123" };
record { int foo; } x = check j.fromJsonWithTypePermissive();

// result is x has value 123
```

Scenario 2 : Optional field has a nill value
```
json j = { foo: null; }`

// succeeds
record { string foo?; } x = check j.fromJsonWithTypePermissive();`

// result is x without foo field
```

We appreciate your opinion on above 2 solutions to find out the best. @hevayo @shafreenAnfar @indikasampath2000 @hasithaa

**Comment by RolandHewage** [comment]
Consider a scenario with insert and partial update operations which is a `POST` and `PATCH` operation in the REST API world.

For example
```
remote isolated function createCustomer(Customer payload) returns CustomerObject|error {}

remote isolated function updateCustomer(string customerId, Customer payload) returns CustomerObject|error {}
```

Let's assume that an API uses the same request body object schema in both situations (For example `Customer` object schema). Let's assume we use `solution 1`. The generated record would be as follows if `email` and `age` are nillable fields.
```
public type Customer record {
    string name;
    string? email = ();
    int? age = ();
}
```

If the user invokes the `createCustomer` operation by setting the `email` field with a value (For example { name: "Shane", email: "shane@wso2.com" }) it will insert that value in the API side. Consider he invokes the `updateCustomer` operation next by setting only the `age` field (For example { name: "Shane", age: 26 }). In this scenario the default value of `email` is set to `()` even if he doesn't configure it. This may overwrite the value of `email` in the API side. Better to consider the above scenario if `Solution 1` will be used in the future.

**Comment by aneeshafedo** [comment]
> Consider a scenario with `insert` and `partial update` operations which is a `POST` and `PATCH` operation in the REST API world.
> 
> For example
> 
> ```
> remote isolated function createCustomer(Customer payload) returns CustomerObject|error {}
> 
> remote isolated function updateCustomer(string customerId, Customer payload) returns CustomerObject|error {}
> ```
> 
> Let's assume that an API uses the same request body object schema in both situations (For example `Customer` object schema). Let's assume we use `solution 1`. The generated record would be as follows if `email` and `age` are nillable fields.
> 
> ```
> public type Customer record {
>     string name;
>     string? email = ();
>     int? age = ();
> }
> ```
> 
> If the user invokes the `createCustomer` operation by setting the `email` field with a value (For example { name: "Shane", email: "[shane@wso2.com](mailto:shane@wso2.com)" }) it will insert that value in the API side. Consider he invokes the `updateCustomer` operation next by setting only the `age` field (For example { name: "Shane", age: 26 }). In this scenario the default value of `email` is set to `()` even if he doesn't configure it. This may overwrite the value of `email` in the API side. Better to consider the above scenario if `Solution 1` will be used in the future.

This scenario can be explicitly represent using `readOnly` and `writeOnly` options in OpenAPI specs. However the support for those features are also not implemented yet in the tool. Please find the related issue [here](https://github.com/ballerina-platform/openapi-tools/issues/512)

**Comment by indikasampath2000** [comment]
@RolandHewage, The update operation should load the `Customer` and do the changes on top of that. 

> If the user invokes the `createCustomer` operation by setting the `email` field with a value (For example { name: "Shane", email: "[shane@wso2.com](mailto:shane@wso2.com)" }) it will insert that value in the API side. Consider he invokes the `updateCustomer` operation next by setting only the `age` field (For example { name: "Shane", age: 26 }). In this scenario the default value of `email` is set to `()` even if he doesn't configure it. This may overwrite the value of `email` in the API side. Better to consider the above scenario if `Solution 1` will be used in the future.

The update operation should load the `Customer` and do the changes on top of that. Wherever the `updateCustomer(customer)` using in an application, the `getCustomer(id)` must be called to get the `Customer`.

 In a partial update, the relevant data only should send to the service. It shouldn't include any other fields in the request. I think we can verify this with our OpenAPI-generated connectors.

Anyway, Solution 2 is promising for the nullable issue. We have rarely seen OpenAPI defined with proper schema catering to all aspects. Mostly, the response will have nullable properties, and data binding will fail in generated clients. Handling this in data binding would be the most suitable solution.

This would be a major improvement required for IDL base OpenAPI client generation. @hevayo @shafreenAnfar, can we prioritize and improve the data binding in the ballerina?
