### ISSUE TITLE
Make OpenAPI CLI consistant with other CLI tools ie bindgen, grpc

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/openapi-tools#97]
**Description:**
Current OpenAPI Cli tools always work on a project. We need to revisit their behavior and make it consistent with other CLI tools like bindgen and grpc. 

Action Items
- [x] Revisit the Open API CLI tools create a design
- [x] Update the user guides
- [x] New design Implementation

**Comment by lnash94** [comment]
Close this issue since the current tool has been updated to consist of other tools.
