### ISSUE TITLE
Support resource functions in OpenAPI Client Generation tool

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/openapi-tools#974]
Currently, resource methods are only allowed for service objects, but they should also be permitted for client objects.
Then after having the support for resource functions we need to provide the option to support the OpenAPI client generation tool for support client resource functions since it is already supported with remote functions.

Therefore we suppose to have this fix https://github.com/ballerina-platform/ballerina-lang/issues/36024 to fulfil the implementation in the opeAPI tool .

**Comment by lnash94** [comment]
- [ ] Finalize the design 
- [ ] Implementation command option to client to enable resource function
- [ ] Update help test
- [ ] Update learn page

**Comment by lnash94** [comment]
Encounter some key points to clarify while mapping the current remote implementation to resource function. 

1. What would be the support from tooling as **the 1st phase** for update 2 among the below two approaches?

example for mock `get` method with a query parameter.
**Current remote implementation** 
```ballerina
remote isolated function listUsers(string status) returns ListUsersResponse|error {
       string resourcePath = string `/users`;
       map<anydata> queryParam = {"status": status};
       resourcePath = resourcePath + check getPathForQueryParam(queryParam);
       ListUsersResponse response = check self.clientEp->get(resourcePath);
       return response;
   }
```
**Approach 01: Replace the remote function signature with the resource function signature and consitste the body** implementation as the previous remote implementation. (This would be only changing function signature)

Replacing remote with **resource** with existing body 
```ballerina
resource isolated function get /users(string status) returns ListUsersResponse|error {
       string resourcePath = string `/users`;
       map<anydata> queryParam = {"status": status};
       resourcePath = resourcePath + check getPathForQueryParam(queryParam);
       ListUsersResponse response = check self.clientEp->get(resourcePath);
       return response;
   }

```
**Approach 02 : Implementing full resource function according to the new design** 
This approach needs to be thinking about several aspects of the mapping, ex: header, request payload etc
example for the mock `get` method with a query parameter.
```ballerina
resource isolated function get /users(string status) returns ListUsersResponse|error {
       ListUsersResponse response = check self.clientEp->/users.get(status);
       return response;
   }
```
---------- 
### Request Body mapping 
3. How do we map the request payload to the new design?
Current code generation for `post` method with request body
```ballerina
remote isolated function addOrder(string orderId, Order payload) returns Order|error {
        string resourcePath = string `/order/${getEncodedUri(orderId)}`;
        http:Request request = new;
        json jsonBody = check payload.cloneWithType(json);
        request.setPayload(jsonBody, "application/json");
        Order response = check self.clientEp->put(resourcePath, request);
        return response;
    }
```
Suggested resource design Do we need to annotate `@http:Payload` in the function signature and client call statement.
```ballerina
resource isolated function post /order/[string orderId](string orderId, @http:Payload Order payload) returns Order|error {
        string resourcePath = string `/order/${getEncodedUri(orderId)}`;
        http:Request request = new;
        json jsonBody = check payload.cloneWithType(json);
        request.setPayload(jsonBody, "application/json");
        Order response = check self.clientEp->/order/[${getEncodedUri(storeId)}].post(request);
         // or 
      Order response = check self.clientEp->/order/[${getEncodedUri(storeId)}].post(request = request);
        return response;
    }
```
-------
### Header Mapping
3. For the header mapping scenarios

- Current  code generation for headers

```ballerina
remote isolated function checkHeaders(string? xTableauAuth = ()) returns Result|error {
        string resourcePath = string `/analytics/connections/${connectionLuid}`;
        map<any> headerValues = {"X-Tableau-Auth": xTableauAuth};
        map<string|string[]> httpHeaders = getMapForHeaders(headerValues);
        Result response = check self.clientEp->get(resourcePath, httpHeaders);
        return response;
    }
```
Suggested code generation with resource.
```ballerina
rsource isolated function get analytics/connections/(@http:Header string? xTableauAuth = ()) returns Result|error {
        string resourcePath = string `analytics/connections/`;
        map<any> headerValues = {"X-Tableau-Auth": xTableauAuth};
        map<string|string[]> httpHeaders = getMapForHeaders(headerValues);
        Result response = check self.clientEp->analytics/connections.get(resourcePath, httpHeaders);
        return response;
    }
```

- Current code generation for the authentication handle via the header.
```ballerina
remote isolated function get /v2/stores/[string storeId]() returns http:Response|error {
       string resourcePath = string `/v2/stores/${getEncodedUri(storeId)}`;
       map<any> headerValues = {"Ocp-Apim-Subscription-Key": self.apiKeyConfig.ocpApimSubscriptionKey};
       map<string|string[]> httpHeaders = getMapForHeaders(headerValues);
       http:Response response = check self.clientEp->get(resourcePath, httpHeaders);
       return response;
   }
```

Suggested designed, can it  be same as without `@http:Header` as the below

```ballerina
remote isolated function get /v2/stores/[string storeId]() returns http:Response|error {
       map<any> headerValues = {"Ocp-Apim-Subscription-Key": self.apiKeyConfig.ocpApimSubscriptionKey};
       map<string|string[]> httpHeaders = getMapForHeaders(headerValues);
       http:Response response = check self.clientEp->/v2/stores/[${getEncodedUri(storeId)}].get(httpHeaders);
       return response;
   }
```
@hevayo, @shafreenAnfar could you please provide some input regarding these points 🙂

**Comment by lnash94** [comment]
As discussed the approaches, decided to give support with **approach 01** under **question 01** as a 1st phase of the tool support.

**Comment by lnash94** [comment]
Encountered issues while implementing the code 

- https://github.com/ballerina-platform/ballerina-lang/issues/36900
- https://github.com/ballerina-platform/ballerina-lang/issues/36898

**Comment by lnash94** [comment]
We are closing this issue with the favor of this PR [https://github.com/ballerina-platform/openapi-tools/pull/1029](https://github.com/ballerina-platform/openapi-tools/pull/1029) 
This resource function support is already added to the update 02.
