### ISSUE TITLE
OpenAPI tool generates a record type to which a value cannot be created

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/openapi-tools#990]
**Description:**
OpenAPI tool generates the following resource function signature for this path https://github.com/tedneward/TicTacToeREST/blob/main/ttt.yaml#L36. 

```
resource function post games(@http:Payload GamesBody payload) 
            returns record {|*http:Created; Game body;|}|http:BadRequest|http:MethodNotAllowed
``` 

It is nearly impossible to create a value for the generated type `record {|*http:Created; Game body;|}`. I created a value using this expression `{status:new http:StatusCreated(), body: game}`. I don't think an external user can figure this out.

**Comment by shafreenAnfar** [comment]
I think it is better if we can generate the below.

```ballerina
resource function post games(@http:Payload Games games) returns CreatedGame|http:BadRequest|http:MethodNotAllowed

type CreatedGame record {| 
   *http:Created; Game body; 
|};
```

**Comment by hevayo** [comment]
In GET resources when we return a record the http library default the status is 200 OK. likewise can we default the status of a POST resource to 201 Created. @shafreenAnfar

**Comment by shafreenAnfar** [comment]
Yeah, that is true. @sameerajayasoma raised this here https://github.com/ballerina-platform/ballerina-standard-library/issues/2469. We will look into that and update the issue.

However, about comment is a generic comment.

**Comment by NipunaRanasinghe** [comment]
@shafreenAnfar AFAIR we decided to use anon records as it was bit tricky to always derive contextual + meaningful names for the response records. @lnash94 I hope we can improve the code generation logic to derive the record names using the schema type and status code. WDYT?

**Comment by hevayo** [comment]
Please see https://ballerina.io/learn/by-example/http-resource-returns.html what is generated is constant with http APIs design so should we look at educating the users on how to return in such cases. ie. One solution is to generate the return statement when we generate the service skeleton.

**Comment by sameerajayasoma** [comment]
@hevayo, the original issue occurs when there are multiple types in the return union type. E.g., `record {|*http:Created; Game body;|}|http:BadRequest|http:MethodNotAllowed`. 

The compiler cannot infer the return type from the expression `{body: foo}`

**Comment by lnash94** [comment]
> @shafreenAnfar AFAIR we decided to use anon records as it was bit tricky to always derive contextual + meaningful names for the response records. @lnash94 I hope we can improve the code generation logic to use named records and, derive the record names based on the schema type and status code. WDYT?

+1 for the suggested way to generate the record names. will proceed with it.

**Comment by sameerajayasoma** [comment]
The third and easy approach would be this:

```ballerina
resource function post games(@http:Payload GamesBody payload) returns record {|*http:Created; Game body;|} | http:BadRequest |http:MethodNotAllowed {
       
        Game game = {id: 1, playerOne: "Harry", playerTwo: "Kane", board: [2,3,4], message: "winning message"};
        record {|*http:Created; Game body;|} response = {body: game};
        return response;
}
```
